const mongoose = require('mongoose');
const connectToMongoDB = require('../config/db');
const riderSchema = new mongoose.Schema({
  username: { type: String, required: true },
  contact: { type: String, required: true },
  email: { type: String, required: true },
  password: { type: String, required: true },//autogenerated password logic to be adddd
 
  recipient: { type: String, default: '', required: false },
  
  delivered_donations: {
    type: [
      {
        donation_id: { type: mongoose.Schema.Types.ObjectId, required: true },
        delivery_status: { type: String, enum: ['pending', 'in_progress', 'delivered'], required: true, default: 'pending'},
        pickup_time: { type: String, required: false},
        delivery_time: { type: String, required: false },
      },
    ],
    default: [],
  },
  number_plate: { type: String, required: true },
  starting_time: { type:String, required: true },
  ending_time: { type: String, required: true },
});

riderSchema.index({ location: '2dsphere' });

const Rider = mongoose.model('Rider', riderSchema);
module.exports = Rider;
